# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [4]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


**First loop** (`for x in arrA`): `x` is a whole row  prints 2 lines, each a doubled array like `[22, 24, 26]`.

**Second loop** (`for y in x`): `y` is a single element  prints 6 individual doubled numbers, one per line.

The difference: the first loop works **row by row**, the second drills into **each individual value**.

In [5]:
# x is the whole row, so x*2 doubles the full row  not just the current y value
# that's why I get the same doubled row printed 3 times per row (once per element)
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [6]:
# stacking arrA on top of itself  axis=0 means adding more rows
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [8]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [9]:
try:
    stacked_array_2 = np.stack((joined_array_1, joined_array_2))
except ValueError as e:
    print(e)
# this fails because np.stack needs both arrays to be the same shape
# joined_array_1 is (4,3) and joined_array_2 is (2,6)  they don't match

all input arrays must have the same shape


In [10]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [11]:
try:
    another_2 = np.concatenate((joined_array_1, arrA), axis=1)
except ValueError as e:
    print(e)
# this fails because axis=1 needs matching row counts
# joined_array_1 has 4 rows, arrA only has 2  can't join them side by side

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2


In [12]:
hstacked = np.hstack((arrA, arrA))
print(hstacked)  # same as axis=1  adds more columns

vstacked = np.vstack((arrA, arrA))
print(vstacked)  # same as axis=0  adds more rows

dstacked = np.dstack((arrA, arrA))
print(dstacked)  # goes 3D  pairs up elements along a new depth axis

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [13]:
# splitting joined_array_1 into 2 equal parts
splitsky = np.split(joined_array_1, 2)
print(splitsky)
# I get 2 arrays, each 2 dimensional (shape 2x3)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [14]:
# joined_array_1 has 4 rows so I need array_split to handle the uneven division
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# I get 3 arrays, each 2 dimensional (two with 2 rows, one with 1 row)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [15]:
# using where() to check each value if even keep it, if odd replace with 'odd'
# % 2 == 0 is my condition to test for even numbers
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [16]:
# creating arrB and sorting it  np.sort sorts each row smallest to largest
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [17]:
# filtering arrB to only get values less than 7
# z is a boolean mask True where condition is met
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [18]:
# same idea but flipped  now I want values greater than or equal to 7
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
