# Exercise 1.B NumPy Random

In [16]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [15]:
import numpy as np

## Generating Random Numbers

In [12]:
# random integers between 1 and 20, 2 elements
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[11 13]


In [13]:
# random integers between 1 and 20, 1 row 2 columns
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[11  1]]


In [4]:
# random floats between 0 and 1, 2 rows 1 column
r_3 = np.random.random(size=(2, 1))
print(r_3)

[[0.56230538]
 [0.63873116]]


In [5]:
# random integers between 20 and 100, 4 rows 5 columns
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[79 29 51 77 66]
 [23 88 85 23 41]
 [22 96 79 97 40]
 [72 41 54 89 54]]


In [6]:
# random floats between 0 and 1, 4 rows 5 columns
r_5 = np.random.random(size=(4, 5))
print(r_5)

[[0.03010303 0.25969693 0.77113939 0.9306078  0.40848625]
 [0.76321113 0.40781301 0.82614605 0.4314112  0.48667505]
 [0.51853194 0.28028766 0.83099836 0.0272995  0.37916399]
 [0.08617628 0.54530121 0.11608923 0.98288404 0.8293654 ]]


## Generating Random Choices from an Array

In [7]:
# storing 12 classmate names in a 1D array
students = np.array(['Alice', 'Bob', 'Carlos', 'Diana', 'Eva', 'Frank',
                     'Grace', 'Henry', 'Isla', 'James', 'Karen', 'Leo'])

In [8]:
# picking one random student to call on
call_on = np.random.choice(students)
print(call_on)

James


In [9]:
# randomly assigning 12 students into 3 rows, 4 columns (3 groups of 4)
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)


[['Leo' 'Henry' 'Grace' 'Grace']
 ['Leo' 'Diana' 'Karen' 'Leo']
 ['Henry' 'Bob' 'Eva' 'Isla']]


## Generating a Normal Distribution

In [10]:
# generating a bell curve with mean=10, std=5, size 4 rows 5 columns
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[ 4.64380681  9.61193576 12.88163521  4.66279524 -1.69322186]
 [ 8.06756525  6.37657881 13.09687637  2.17012262 13.19205995]
 [ 7.67717594  5.90456353 14.09983872  7.57234262 15.11942926]
 [ 9.99497528 15.76856724 10.81719452 11.24803359  9.12677522]]
