# Exercise 1.B NumPy Random

In [2]:
import numpy as np

## Generating Random Numbers

In [3]:
# random integers between 1 and 20, 2 elements
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[12 16]


In [4]:
# random integers between 1 and 20, 1 row 2 columns
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[6 4]]


In [5]:
# random floats between 0 and 1, 2 rows 1 column
r_3 = np.random.random(size=(2, 1))
print(r_3)

[[0.10067648]
 [0.6279768 ]]


In [6]:
# random integers between 20 and 100, 4 rows 5 columns
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[78 52 43 47 55]
 [95 80 89 74 58]
 [57 23 29 85 28]
 [96 91 63 37 75]]


In [7]:
# random floats between 0 and 1, 4 rows 5 columns
r_5 = np.random.random(size=(4, 5))
print(r_5)

[[0.79812218 0.68999436 0.65718129 0.61449718 0.32787082]
 [0.99448719 0.03140562 0.90951206 0.53005418 0.34570968]
 [0.56257474 0.95165813 0.01952612 0.64309181 0.90286279]
 [0.34064761 0.23896717 0.42638097 0.28804357 0.17919185]]


## Generating Random Choices from an Array

In [9]:
# storing 12 classmate names in a 1D array
students = np.array(['Alice', 'Bob', 'Carlos', 'Diana', 'Eva', 'Frank',
                     'Grace', 'Henry', 'Isla', 'James', 'Karen', 'Leo'])

In [10]:
# picking one random student to call on
call_on = np.random.choice(students)
print(call_on)

Eva


In [11]:
# randomly assigning 12 students into 3 rows, 4 columns (3 groups of 4)
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)


[['Alice' 'Grace' 'Henry' 'Grace']
 ['Isla' 'James' 'Alice' 'Frank']
 ['James' 'Carlos' 'Frank' 'Grace']]


## Generating a Normal Distribution

In [12]:
# generating a bell curve with mean=10, std=5, size 4 rows 5 columns
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[10.95376441  3.85053368  7.28799091 10.32350966 10.36824143]
 [ 6.76646295  2.37682501  4.64693703  9.57214414 16.838028  ]
 [ 8.40047695  6.88137501 17.18985316 13.6094093  13.55283648]
 [ 8.19949114 18.33346275 16.75192051 16.86212786  8.37893104]]
