# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
# Reusing r_1 through r_5 from Exercise 1.B
r_1 = np.random.randint(1, 10, size=5)
r_2 = np.random.randint(1, 10, size=(2, 5))
r_3 = np.random.uniform(1, 10, size=(3, 4))
r_4 = np.random.randint(1, 10, size=(2, 5))
r_5 = np.random.randint(1, 10, size=(3, 3))
print(r_1, r_2, r_3, r_4, r_5, sep='\n')

[3 6 3 2 9]
[[4 5 5 7 5]
 [6 9 5 1 1]]
[[7.58497031 1.12718838 4.8980346  1.57540867]
 [7.05007745 5.99481979 1.01873244 3.89473259]
 [6.39136803 2.83856941 6.87792351 7.3675368 ]]
[[6 7 7 5 6]
 [2 9 8 8 9]]
[[7 4 5]
 [5 8 8]
 [1 6 5]]


## Permutations

In [3]:
print('r_4 before shuffle:\n', r_4)

r_4 before shuffle:
 [[6 7 7 5 6]
 [2 9 8 8 9]]


In [4]:
np.random.shuffle(r_4)  # modifies r_4 in place
print('r_4 after shuffle:\n', r_4)

r_4 after shuffle:
 [[2 9 8 8 9]
 [6 7 7 5 6]]


The elements were shuffled along axis 0, meaning the rows swapped positions. The values inside each row stayed in their original order  only the rows themselves moved.

In [5]:
new_shuffle = np.random.permutation(r_4)  # returns new array, r_4 unchanged
print('new_shuffle:\n', new_shuffle)
print('r_4 (unchanged):\n', r_4)

new_shuffle:
 [[6 7 7 5 6]
 [2 9 8 8 9]]
r_4 (unchanged):
 [[2 9 8 8 9]
 [6 7 7 5 6]]


**shuffle vs permutation:** Use `shuffle` to reorder the original array in place. 
Use `permutation` to get a shuffled copy without changing the original.

## Mathematical Operations

In [6]:
print('r_1:', r_1, '| shape:', r_1.shape)
print('r_2:\n', r_2, '| shape:', r_2.shape)
result = np.add(r_1, r_2)
print('r_1 + r_2:\n', result, '| shape:', result.shape)

r_1: [3 6 3 2 9] | shape: (5,)
r_2:
 [[4 5 5 7 5]
 [6 9 5 1 1]] | shape: (2, 5)
r_1 + r_2:
 [[ 7 11  8  9 14]
 [ 9 15  8  3 10]] | shape: (2, 5)


In [7]:
print('r_1:', r_1, '| shape:', r_1.shape)
print('r_3:\n', r_3, '| shape:', r_3.shape)

try:
    result = np.add(r_1, r_3)
    print('r_1 + r_3:\n', result, '| shape:', result.shape)
except ValueError as e:
    print('Error:', e)
# r_1 is shape (5,) and r_3 is shape (3,4) columns don't match so broadcasting fails

r_1: [3 6 3 2 9] | shape: (5,)
r_3:
 [[7.58497031 1.12718838 4.8980346  1.57540867]
 [7.05007745 5.99481979 1.01873244 3.89473259]
 [6.39136803 2.83856941 6.87792351 7.3675368 ]] | shape: (3, 4)
Error: operands could not be broadcast together with shapes (5,) (3,4) 


In [8]:
print('r_2:\n', r_2, '| shape:', r_2.shape)
print('r_4:\n', r_4, '| shape:', r_4.shape)
result = np.add(r_2, r_4)
print('r_2 + r_4:\n', result, '| shape:', result.shape)

r_2:
 [[4 5 5 7 5]
 [6 9 5 1 1]] | shape: (2, 5)
r_4:
 [[2 9 8 8 9]
 [6 7 7 5 6]] | shape: (2, 5)
r_2 + r_4:
 [[ 6 14 13 15 14]
 [12 16 12  6  7]] | shape: (2, 5)


In [9]:
# r_1 (5,) + r_4 (2,5)  works, r_1 broadcasts across both rows of r_4
try:
    print('r_1 + r_4:\n', np.add(r_1, r_4))
except ValueError as e:
    print('r_1 + r_4 error:', e)

# r_2 (2,5) + r_4 (2,5)  same shape, works fine
try:
    print('r_2 + r_4:\n', np.add(r_2, r_4))
except ValueError as e:
    print('r_2 + r_4 error:', e)

# r_3 (3,4) + r_4 (2,5)  incompatible shapes, fails
try:
    print('r_3 + r_4:\n', np.add(r_3, r_4))
except ValueError as e:
    print('r_3 + r_4 error:', e)

r_1 + r_4:
 [[ 5 15 11 10 18]
 [ 9 13 10  7 15]]
r_2 + r_4:
 [[ 6 14 13 15 14]
 [12 16 12  6  7]]
r_3 + r_4 error: operands could not be broadcast together with shapes (3,4) (2,5) 


In [10]:
print(np.add(np.array([1]), r_4))

[[ 3 10  9  9 10]
 [ 7  8  8  6  7]]


In [11]:
print(np.add(np.array([[1]]), r_4))

[[ 3 10  9  9 10]
 [ 7  8  8  6  7]]


In [12]:
print(np.add(np.array([1,1,1,1,1]), r_4))


[[ 3 10  9  9 10]
 [ 7  8  8  6  7]]


In [13]:
# [[1],[1]] shape (2,1)  broadcasts across the 5 columns
try:
    print(np.add(np.array([[1],[1]]), r_4))
except Exception as e:
    print('Error:', e)

[[ 3 10  9  9 10]
 [ 7  8  8  6  7]]


**How broadcasting works:** NumPy stretches a smaller array to fit a larger one when 
dimensions are compatible (sizes match or one is 1). The result always takes the shape 
of the larger array.

## Rounding

In [14]:
print('r_3:\n', r_3)

r_3:
 [[7.58497031 1.12718838 4.8980346  1.57540867]
 [7.05007745 5.99481979 1.01873244 3.89473259]
 [6.39136803 2.83856941 6.87792351 7.3675368 ]]


In [15]:
print(np.trunc(r_3))    # drops the decimal, rounds toward zero

[[7. 1. 4. 1.]
 [7. 5. 1. 3.]
 [6. 2. 6. 7.]]


In [16]:
print(np.fix(r_3))      # same as trunc, rounds toward zero

[[7. 1. 4. 1.]
 [7. 5. 1. 3.]
 [6. 2. 6. 7.]]


In [17]:
print(np.floor(r_3))    # rounds down toward negative infinity

[[7. 1. 4. 1.]
 [7. 5. 1. 3.]
 [6. 2. 6. 7.]]


In [18]:
print(np.ceil(r_3))     # rounds up toward positive infinity

[[8. 2. 5. 2.]
 [8. 6. 2. 4.]
 [7. 3. 7. 8.]]


In [19]:
print(np.round(r_3, 2)) # standard rounding to 2 decimal places

[[7.58 1.13 4.9  1.58]
 [7.05 5.99 1.02 3.89]
 [6.39 2.84 6.88 7.37]]


## Cumulative Operations

In [20]:
print('r_4:\n', r_4)

r_4:
 [[2 9 8 8 9]
 [6 7 7 5 6]]


In [21]:
print('Sum of all values in r_4:', np.sum(r_4))

Sum of all values in r_4: 67


In [22]:
print('Sum along axis 0 (column totals):', np.sum(r_4, axis=0))

Sum along axis 0 (column totals): [ 8 16 15 13 15]


In [23]:
print('Sum along axis 1 (row totals):', np.sum(r_4, axis=1))

Sum along axis 1 (row totals): [36 31]


In [24]:
print('Cumulative sum (rolling total, flattened):', np.cumsum(r_4))

Cumulative sum (rolling total, flattened): [ 2 11 19 27 36 42 49 56 61 67]


In [25]:
print('Cumulative sum along axis 0:\n', np.cumsum(r_4, axis=0))

Cumulative sum along axis 0:
 [[ 2  9  8  8  9]
 [ 8 16 15 13 15]]


## Grocery Problem

In [26]:
# [vegetables, fruits, snacks, beverages]
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])
print('bag1:', bag1)
print('bag2:', bag2)

bag1: [2 3 4 0]
bag2: [4 0 1 2]


In [27]:
totals = np.sum([bag1, bag2], axis=1)
print(f'The first bag contains {totals[0]} items, and the second bag contains {totals[1]} items.')

The first bag contains 9 items, and the second bag contains 7 items.


In [28]:
by_category = np.add(bag1, bag2)
print(f'There are {by_category[0]} vegetables, {by_category[1]} fruits, {by_category[2]} boxes of snacks, and {by_category[3]} beverages in the two grocery bags.')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [29]:
ali = np.array([5, 4, 6, 4, 2])  # Mon–Fri

In [30]:
ben = np.array([0, 5, 5, 3, 4])  # 0 = missed Monday

In [31]:
carla = np.array([3, 6, 0, 3, 4])  # 0 = missed Wednesday

In [32]:
all_knocks = np.array([ali, ben, carla])  # rows = people, columns = days
print('all_knocks:\n', all_knocks)

all_knocks:
 [[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [33]:
per_person = np.sum(all_knocks, axis=1)   # sum each row = weekly total per person
group_total = np.sum(all_knocks)
print(f'Ali knocked on {per_person[0]} doors, Ben on {per_person[1]}, Carla on {per_person[2]}.')
print(f'The group collectively knocked on {group_total} doors.')

Ali knocked on 21 doors, Ben on 17, Carla on 16.
The group collectively knocked on 54 doors.


In [34]:
daily_totals = np.sum(all_knocks, axis=0)  # total doors per day across the whole group
rolling_daily = np.cumsum(daily_totals)    # rolling total of doors day by day
rolling_votes = rolling_daily * 0.5        # 1 estimated vote per every 2 door knocks

days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
for day, votes in zip(days, rolling_votes):
    print(f'{day}: {int(votes)} estimated votes turned out so far')

Monday: 4 estimated votes turned out so far
Tuesday: 11 estimated votes turned out so far
Wednesday: 17 estimated votes turned out so far
Thursday: 22 estimated votes turned out so far
Friday: 27 estimated votes turned out so far
